### ISSUE TITLE
To err or fail

### ISSUE THREAD

**Issue by UWN** [bakaq/constrained.pl#5]
How much should predicates that actually implement constraints produce errors? In Prolog IV, constraints do not produce any type or domain error at all but instead they fail, as there is no instance that holds.

Currently:

```
?- functor_spec(T,F,A), F = 1*1, A= a.
   error(type_error(atomic,1*1),functor/3).
?- functor_spec(T,F,A), A= a, F = 1*1.
   error(type_error(integer,a),length/2).
?- functor_spec(T,F,A), F-A = 1*1-a.
   false.
?- F-A = 1*1-a.
   F = 1*1, A = a.
```

So, if unification is done in an explicitly sequential manner, there are errors. But when they are executed simultaneously, there is "silent" failure.

The way how unification is executed exactly is often very implementation dependent. The only requirement by the standard is the respect of the NSTO-property. But not more than that.

With above behaviour chances are that seemingly unrelated program modifications lead from failure to error or back. So probably the best way to go is to opt for always failure.

Compare this to cases where already failure is chosen:
```
?- functor(T,2,2).
   error(type_error(atomic,2),functor/3).
?- functor_spec(T,2,2).
   false.

**Comment by bakaq** [comment]
I think I also lean more to the side of failure instead of error. I feel there is definitively a trade-off here, but I don't really understand the upsides of errors enough to think clearly about it. I guess with error you can know _why_ a constraint wasn't satisfied, but just failing is more declarative, as you said it means that "there is no instance that holds".

**Comment by bakaq** [comment]
I think I'm actually going to close this when the queries you gave are consistent with always failing.

**Comment by UWN** [comment]
Errors like type errors necessitate that the exact execution order is fixed. Otherwise, they often lead to confusion. In ISO, there is a fixed well-defined order. And, even more so, prior to, say, 1993, there were not that clear alternatives around. Even `dif/2` (first implemented 1975-05 in système Œdipe, that is, prior to the existence of Prolog) or any other constraint mechanism was simply too immature. Even now [there are differences](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/dif).

Failure has the advantage that one can use declarative methods to locate the error. Like [generalizations](https://stackoverflow.com/a/30791637/772868).

**Comment by UWN** [comment]
... on the other hand, the most common `clpfd`/`clpz` implementations do produce errors, and it seems this is really what one expects in these areas:

```
?- X = a, X #> 0.
   error(domain_error(clpz_expression,a),unknown(a)-1).
?- X = a, #X #> 0.
   error(type_error(integer,a),must_be/2).
?- #X #> 0, X = a.
   error(type_error(integer,a),unknown(a)-1).
```

But then, finite domain variables are often only connected to integers (in error free programs).

**Comment by UWN** [comment]
What about looking into the implementation of `dif/2`? Currently, there are several unfixed issues in Scryer. The big advantage would be that its specification is quite clear. So no need to guess around new names and the like. But certainly, I should warn you, it is far from trivial. (And I mean just `dif/2` together with terms. Not `dif/2` and other constraints.) To give you an idea what this is about, SWI has [never had a correct implementation](https://github.com/SWI-Prolog/issues/issues?q=is%3Aissue+dif%2F2). SICStus has space leaks. Scryer has leaks and lots of unnecessary residuals. You get it. Ah, one added complexity would be that Scryer has three different unification modes (terms (with occurs-check), terms (with errors), and trees (rational, infinite)). It should work accordingly in all of them. If interested, start here: https://github.com/mthom/scryer-prolog/issues/135. At least I can promise you to [thoroughly test it](https://github.com/issues?q=is%3Aissue+author%3AUWN+dif%2F2). In any case, this would give you a quite good introduction into atvs.

**Comment by bakaq** [comment]
I used the Scryer implementation of `dif/2` as a reference of how to use attributed variables, because I didn't find much documentation about it (the closest is the SICStus documentation, but there are some differences such as `attribute_goals//1` being a DCG). I think I now understand how it works well enough to give `dif/2` a serious look.

**Comment by UWN** [comment]
Better sources for studying are `clpz` and maybe even more so `clpb`.

**Comment by bakaq** [comment]
> on the other hand, the most common `clpfd`/`clpz` implementations do produce errors

I've been trying to integrate clpz to deal with integer constraints in this library and this has become a problem. Now queries can give type errors when interacting with integer constrained variables:

```
?- functor_c(A, B, C), B = a, C = 1*1.
   error(type_error(integer,1*1),unknown(1*1)-1).
```

I think this is a trade-off that is worth it to benefit from the power of clpz.
