### ISSUE TITLE
Invalid syntax used

### ISSUE THREAD

**Issue by UWN** [bakaq/constrained.pl#7]
```
(#=..)(Term, [Functor|Args]) :-
   ... .
```

which is [invalid syntax](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing#321)
and specific to Scryer https://github.com/mthom/scryer-prolog/issues/2033

Use instead functional notation (6.3.3):

```
#=..(Term, Functor|Args]) :-
   ... .
```

**Comment by bakaq** [comment]
Makes sense.  I did that way because it made the syntax highlighting in Vim better. I changed highlighters now though, so that doesn't matter anymore.
