### ISSUE TITLE
catch/3-all may mask real errors

### ISSUE THREAD

**Issue by UWN** [bakaq/constrained.pl#8]
```
    catch(enforce_constraints_(Var, Functor, Arity, Args), _, false).
```

The intention is probably to catch type- and domain-errors. But not other errors. What, if there is a resource error? Currently, Scryer just aborts, but more mature systems like SICStus and SWI do produce this error. (And for robust server code this will be needed in Scryer too.)

The cleanest (but currently very inefficient) way is to say:

```
   catch(catch(Yourgoal_0, error(type_error(_,_),_), false), error(domain_error(_,_),_), false).
```

**Comment by bakaq** [comment]
> The cleanest (but currently very inefficient) way

Why exactly is it inefficient? I can't see any other way of doing that except something like this:

```
catch(
    Goal,
    error(Error,_),
    (   Error /= type_error(_,_),
        Error /= domain_error(_,_)
    )
).
```

**Comment by UWN** [comment]
Your suggestion is masking other errors too, it makes now the goal succeed in such cases. Instead the exception should be propagated.

(Inefficient is the current implementation of `catch/3`. There is much too much overhead involved. For simple `Recovery` like false, much less is needed. But this is a performance issue only)
